POST http://localhost:3030/summarizations
Content-Type: application/json

{
  "title": "learn about node.js",
  "link": "https://www.youtube.com/watch?v=2SUwOgmvzK4",
  "startAt": 100,
  "endAt": 300
}

###

GET http://localhost:3030/summarizations

###

GET http://localhost:3030/summarizations?search=node

###

PUT http://localhost:3030/summarizations/:id
Content-Type: application/json

{
  "title": "learn about javascript",
  "link": "https://",
  "startAt": 100,
  "endAt": 300
}

###

DELETE http://localhost:3030/summarizations/:id